### ISSUE TITLE
Feedback: The KEY on youku cannot be obtained

### ISSUE THREAD

**Issue by hjkow** [FoxRefire/wvg#14] opened 2024-05-12 09:59 UTC
**Google translated**

I used Google Chrome and Firefox browsers respectively, and when the extension was running, I selected Youku, but after clicking Result, the cursor was always in a circle state. KEY cannot appear. I hope the author can fix it. Thank you very much!
<details>
<summary>Original comment</summary>

我分别使用了Google Chrome和Firefox浏览器，并在扩展运行时，选择了Youku，但是点击Result后，光标一直是圆圈状态。无法出现KEY，希望作者能够修复一下，万分感谢！

</details>

**Comment by FoxRefire** [comment] 2024-05-13 16:19
Logs?

1.Logs from Guesser window
2.Logs from Video window
3.HAR from Video window after extension executed

**Comment by FoxRefire** [comment] 2024-05-14 07:15
Closed due to inactivity
The issue will reopened when activity occurs.

**Comment by hjkow** [comment] 2024-05-14 07:35
> 日志？
> 
> 1.来自猜测窗口的日志 2.来自视频窗口的日志 3.执行扩展后来自视频窗口的 HAR
![image](https://github.com/FoxRefire/wvg/assets/90509078/c384b810-bd22-4fd0-bfd1-3b8441d8e046)

![image](https://github.com/FoxRefire/wvg/assets/90509078/862bad2c-eb2d-434f-97d1-f0c0cda668d4)


Can you help me take a look

**Comment by FoxRefire** [comment] 2024-05-14 08:16
Go to the Network tab and check and let me know the response of the request made by the extension

**Comment by hjkow** [comment] 2024-05-14 08:24
> Go to the Network tab and check and let me know the response of the request made by the extension

![image](https://github.com/FoxRefire/wvg/assets/90509078/d7a4f4ad-82a2-4e10-b454-ad6ccafc8134)
![image](https://github.com/FoxRefire/wvg/assets/90509078/ce6aa435-fcd3-4734-9cd7-7df649afad44)

As shown in the above figure, Youku cannot obtain it

**Comment by FoxRefire** [comment] 2024-05-14 08:27
Need response body of failed request

**Comment by hjkow** [comment] 2024-05-14 13:15
> 请求失败的响应体

There is no abnormal response subject, but the key cannot be obtained, which feels a bit stuck

**Comment by FoxRefire** [comment] 2024-05-14 18:36
Then, open `python/schemes/Youku.py` and insert line `print("DEBUG:"+res)` after line 8 of the file.
And could you send console log of Guesser window, not video window.

**Comment by hjkow** [comment] 2024-05-15 07:28
> 然后，打开文件`python/schemes/Youku.py`并在第 8 行之后插入行`print("DEBUG:"+res)`。 您能否发送 Guesser 窗口的控制台日志，而不是视频窗口。

![QQ截图20240515152638](https://github.com/FoxRefire/wvg/assets/90509078/7c47d9e0-683d-4206-a2f7-685ca0a60419)
![QQ截图20240515152700](https://github.com/FoxRefire/wvg/assets/90509078/17e4ac5f-0bbe-4641-ba6a-f820954df28d)

**Comment by dreammu** [comment] 2024-06-08 12:40
> Need response body of failed request

![image](https://github.com/FoxRefire/wvg/assets/84692291/07664cf5-5ead-4018-ad46-87b8b4267336)
Basically "invalid argument" in Chinese

![image](https://github.com/FoxRefire/wvg/assets/84692291/5114fafe-7830-44b6-a2ef-cfd6394937ca)
browser request
![image](https://github.com/FoxRefire/wvg/assets/84692291/7ab0ffed-5b0c-4184-ba7a-6b4fdb62f4e3)
wvg request

It looks like wvg's request incorrectly adds `['` and `']`

**Comment by FoxRefire** [comment] 2024-06-08 16:21
Closed in #24

**Comment by dreammu** [comment] 2024-06-09 07:06
I'm requesting to reopen this issue, this is different from the situation I mentioned before. His situation is sending a request but not receiving a response, which I also encountered but I can't reproduce it stably.

**Comment by FoxRefire** [comment] 2024-07-25 19:44
>  I also encountered but I can't reproduce it stably.

@dreammu @hjkow
Is this problem still occurring?
The random problems that have been occurring since fix #24 were probably caused by corsFetch, which has already been fixed.
If the issue is still persisting, I will keep the issue open, but if we are sure the issue is no longer occurring or there is no response, I will close the issue.

**Closed as completed** 2024-07-27 01:39 UTC
Labels: bug, scheme, completed
